// This file will be auto-generated by Supabase CLI in production
// For now, we'll use a simple placeholder type
export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: any
        Insert: any
        Update: any
      }
    }
  }
}
