export function ExampleEmails() {
  const emails = [
    {
      investor: 'Sarah Chen',
      firm: 'Sequoia Capital',
      subject: 'AI for fundraising - 40% WoW growth',
      body: `Read your recent post on "Why vertical AI tools will dominate" - especially resonated with your point about workflow integration over generic chatbots.

Building ReachRound, an AI-powered investor outreach platform. We've hit 200 early signups with 40% week-over-week growth in our first month.

Raising $500K pre-seed; given your investments in Ramp and Mercury, would love your take on our approach to automating founder-investor matching vs. traditional intro networks.

Do you have 15 minutes next week to share thoughts on our go-to-market strategy?`,
      tags: ['Fintech', 'AI', 'Pre-seed'],
    },
    {
      investor: 'Mark Johnson',
      firm: 'a16z',
      subject: 'YC-backed fundraising tool - $50K MRR',
      body: `Saw your tweet about backing tools that save founders time during fundraising. That's exactly what we're building at ReachRound.

We're an AI platform that researches investors and writes personalized outreach emails - hit $50K MRR with 85% month-over-month growth, backed by Y Combinator.

Closing our $2M seed round; given your work with Dover and Deel, would value your perspective on scaling sales-assisted vs. self-serve for B2B tools.

Would you have 20 minutes next Tuesday or Wednesday to discuss our scaling strategy?`,
      tags: ['SaaS', 'YC-backed', 'Seed'],
    },
  ]

  return (
    <section className="py-20 px-4">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-foreground dark:text-foreground mb-4">
            Real Emails Generated by ReachRound
          </h2>
          <p className="text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
            Each email is personalized based on deep research about the investor&apos;s recent activity, portfolio, and investment thesis.
          </p>
        </div>

        <div className="grid gap-8 lg:grid-cols-2">
          {emails.map((email, index) => (
            <div
              key={index}
              className="bg-card dark:bg-card border border-border dark:border-border rounded-xl overflow-hidden hover:border-gray-700 dark:hover:border-gray-700 transition-colors"
            >
              {/* Email Header */}
              <div className="bg-gray-50 dark:bg-gray-900 border-b border-border dark:border-border px-6 py-4">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <div className="text-lg font-semibold text-foreground dark:text-foreground">
                      {email.investor}
                    </div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      {email.firm}
                    </div>
                  </div>
                  <div className="flex gap-2">
                    {email.tags.map((tag, tagIndex) => (
                      <span
                        key={tagIndex}
                        className="text-xs px-2 py-1 bg-primary-500/10 text-primary-500 rounded"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="text-sm text-gray-900 dark:text-gray-200">
                  <span className="font-medium">Subject: </span>
                  {email.subject}
                </div>
              </div>

              {/* Email Body */}
              <div className="px-6 py-5">
                <div className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-line leading-relaxed">
                  {email.body}
                </div>
              </div>

              {/* Email Footer */}
              <div className="bg-gray-50 dark:bg-gray-900 border-t border-border dark:border-border px-6 py-3">
                <div className="flex items-center gap-4 text-xs text-gray-500 dark:text-gray-500">
                  <div className="flex items-center gap-1">
                    <span>✓</span>
                    <span>Personalized hook</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span>✓</span>
                    <span>Specific metrics</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span>✓</span>
                    <span>Clear CTA</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="text-sm text-gray-500 dark:text-gray-500">
            These are real examples of emails generated by our AI, with names changed for privacy.
          </p>
        </div>
      </div>
    </section>
  )
}
